name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Delete existing Docker container
        run: sudo docker rm -f dweb
      - name: Pull Docker Image from Docker hub
        run: sudo docker pull crispycacao/songdo:latest
      - name: Execute Docker Container
        run: sudo docker run -d -p 80:3000 --name dweb crispycacao/songdo:latest